### ISSUE TITLE
Incomprehensible outcome characters 

### ISSUE THREAD

**Issue by albagc** [jspaaks/2022-ieee#1]
Hi! 

I just run fairtally with my repo and got these results. Could you help me get the normal symbols? 

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/30121953/195401966-21948041-0a95-4bfa-a58d-ace08abbb8b5.png">

**Comment by Saad31e** [comment]
S3bei

**Comment by jspaaks** [comment]
Moved issue to fairtally's repo: https://github.com/fair-software/fairtally/issues/94, closing this one.
